// Submit the test file to the API

GET {{LAMBDA_URL}} HTTP/1.1
Content-Type: text/plain
Authorization: BRADLEY.SOFTWARE

< ./testing01.txt

###

// Test with an invalid authorization header, should return 401 Unauthorized

GET {{LAMBDA_URL}} HTTP/1.1
Content-Type: text/plain
Authorization: BRADLEY.SOFTWARE.INVALID

The patient had a nice drink today and feels much better.

###

// Test with no data submitted, should return 400 Bad Request

GET {{LAMBDA_URL}} HTTP/1.1
Content-Type: text/plain
Authorization: BRADLEY.SOFTWARE

###